### ISSUE TITLE
The Grand Rewrite

### ISSUE THREAD

**Issue by mkaput** [starkware-libs/cairo#5355]
The architecture of CairoLS has many flaws that accumulated into a cause of many problems over time. It's time to fix it.

- [x] Implement proper logging facilities.
- [x] Unlock mutexes and chop `refresh_diagnostics` routine into smaller chunks of work.
- [x] Wrap `RootDatabase` into `AnalysisHost` / `Analysis` structures
- [ ] Revise _Scarb is resolving_ flow (rel #5354) - to be fixed by _New Project Model_ project
- [ ] Rewrite LS state into a _mutable state_ and _snapshot_ structures and use coarse locking (either get entire state as mutable, or lock for a short time to produce a snapshot and defer work into a blocking background thread) depending on the request coming from the editor
- [ ] Support salsa cancellation in all operations
- [ ] Rewrite from `tower-lsp` to `lsp-server` (https://github.com/ebkalderon/tower-lsp/issues/284)
- [ ] Rewrite approach to the VFS and files overrides (rel #3985)
- [ ] Introduce GC mechanisms into Salsa database.
- [x] Create a test suite.

**Comment by mkaput** [comment]
I'm converting this issue into a milestone: https://github.com/starkware-libs/cairo/milestone/1
